---
# Source: vector/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vector-aggregator
  labels:
    helm.sh/chart: vector-0.16.0
    app.kubernetes.io/name: vector
    app.kubernetes.io/instance: vector
    app.kubernetes.io/component: Aggregator
    app.kubernetes.io/version: "0.24.1-distroless-libc"
    app.kubernetes.io/managed-by: Helm
    
automountServiceAccountToken: true
---
# Source: vector/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-aggregator
  labels:
    helm.sh/chart: vector-0.16.0
    app.kubernetes.io/name: vector
    app.kubernetes.io/instance: vector
    app.kubernetes.io/component: Aggregator
    app.kubernetes.io/version: "0.24.1-distroless-libc"
    app.kubernetes.io/managed-by: Helm
    
data:
  aggregator.yaml: |
    data_dir: /vector-data-dir
    api:
      enabled: true
      address: 127.0.0.1:8686
      playground: false
    sources:
      datadog_agent:
        address: 0.0.0.0:8282
        type: datadog_agent
      fluent:
        address: 0.0.0.0:24224
        type: fluent
      internal_metrics:
        type: internal_metrics
      logstash:
        address: 0.0.0.0:5044
        type: logstash
      splunk_hec:
        address: 0.0.0.0:8080
        type: splunk_hec
      statsd:
        address: 0.0.0.0:8125
        mode: tcp
        type: statsd
      syslog:
        address: 0.0.0.0:9000
        mode: tcp
        type: syslog
      vector:
        address: 0.0.0.0:6000
        type: vector
        version: "2"
    sinks:
      prom_exporter:
        type: prometheus_exporter
        inputs: [internal_metrics]
        address: 0.0.0.0:9090
      stdout:
        type: console
        inputs: [datadog_agent, fluent, logstash, splunk_hec, statsd, syslog, vector]
        encoding:
          codec: json
---
# Source: vector/templates/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: vector-aggregator
  labels:
    helm.sh/chart: vector-0.16.0
    app.kubernetes.io/name: vector
    app.kubernetes.io/instance: vector
    app.kubernetes.io/component: Aggregator
    app.kubernetes.io/version: "0.24.1-distroless-libc"
    app.kubernetes.io/managed-by: Helm
    
spec:
  replicas: 1
  podManagementPolicy: OrderedReady
  selector:
    matchLabels:
      app.kubernetes.io/name: vector
      app.kubernetes.io/instance: vector
      app.kubernetes.io/component: Aggregator
  serviceName: vector-aggregator-headless
  template:
    metadata:
      annotations:
        checksum/config: 4bb0b211de998472dfa64fe515ba1796c1cc4831af9955b245d6757fb277df8f
      labels:
        app.kubernetes.io/name: vector
        app.kubernetes.io/instance: vector
        app.kubernetes.io/component: Aggregator
        vector.dev/exclude: "true"
    spec:
      serviceAccountName: vector-aggregator
      dnsPolicy: ClusterFirst
      containers:
        - name: vector
          image: "timberio/vector:0.24.1-distroless-libc"
          imagePullPolicy: IfNotPresent
          args:
            - --config-dir
            - /etc/vector/
          env:
          ports:
            - name: datadog-agent
              containerPort: 8282
              protocol: TCP
            - name: fluent
              containerPort: 24224
              protocol: TCP
            - name: logstash
              containerPort: 5044
              protocol: TCP
            - name: splunk-hec
              containerPort: 8080
              protocol: TCP
            - name: statsd
              containerPort: 8125
              protocol: TCP
            - name: syslog
              containerPort: 9000
              protocol: TCP
            - name: vector
              containerPort: 6000
              protocol: TCP
            - name: prom-exporter
              containerPort: 9090
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: "/vector-data-dir"
            - name: config
              mountPath: "/etc/vector/"
              readOnly: true
      terminationGracePeriodSeconds: 60
      volumes:
        - name: data
          emptyDir: {}
        - name: config
          projected:
            sources:
              - configMap:
                  name: vector-aggregator
  volumeClaimTemplates:
