apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ingress-gateways.yaml
- authentication.yaml
- authorization.yaml
- external-gateway.yaml
- internal-gateway.yaml
