apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-only-ingress-gateways
spec:
  selector:
    matchLabels:
      app: hello
  action: DENY
  rules:
  - from:
    - source:
        notPrincipals:
        - cluster.local/ns/istio-ingress/sa/external-ingress-gateway-service-account
        - cluster.local/ns/istio-ingress/sa/internal-ingress-gateway-service-account
