apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: local-applications
  namespace: argocd
spec:
  generators:
  - git:
      repoURL: https://github.com/00rg/state.git
      revision: HEAD
      directories:
      # - path: config/platform/istio-ingress/overlays/local
      # - path: config/platform/istio-operator/overlays/local
      # - path: config/platform/istio-system/overlays/local
      - path: config/services/hello/overlays/local
      - path: config/services/httpbin/overlays/local
  template:
    metadata:
      name: '{{path[3]}}'
    spec:
      project: default
      source:
        repoURL: https://github.com/00rg/state.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
