apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../applications/platform/istio-ingress/overlays/local
- ../../applications/platform/istio-operator/overlays/local
- ../../applications/platform/istio-system/overlays/local
- ../../applications/services/hello/overlays/local
- ../../applications/services/httpbin/overlays/local
components:
- ../../components/non-production
- ../../components/ap-southeast-2
