apiVersion: v1
kind: Service
metadata:
  name: goodbye
  labels:
    app: goodbye
    service: goodbye
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: goodbye
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: goodbye-external
spec:
  hosts:
  - api.00rg.com
  gateways:
  - istio-ingress/external-gateway
  http:
  - match:
    - uri:
        prefix: /goodbye/
    rewrite:
      uri: /
    route:
    - destination:
        host: goodbye
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: goodbye-internal
spec:
  hosts:
  - api.internal.00rg.com
  gateways:
  - istio-ingress/internal-gateway
  http:
  - match:
    - uri:
        prefix: /goodbye/
    rewrite:
      uri: /
    route:
    - destination:
        host: goodbye
